### ISSUE TITLE
packit trigger

### ISSUE THREAD

**Issue by sparticvs** [sparticvs/owasp-threat-dragon-rpm#6]
hi packit, you are a big deal around here...

**Comment by TomasTomecek** [comment]
Sorry, we do not support retriggering commit builds via issue comments, even though it's a good suggestion. You can find the results of builds once you click on a commit: https://github.com/sparticvs/owasp-threat-dragon-rpm/runs/8856079691

We also suggest setting up builds for pull requests, those are the easiest to work with :)

**Comment by sparticvs** [comment]
@TomasTomecek I had to make changes to the permissions in Copr itself which didn't require a code change to re-run. These were to work through those issues, but at the time I didn't fully understand what they were to write out a useful ticket.

**Comment by TomasTomecek** [comment]
https://packit.dev/docs/faq/#how-can-i-contact-you

Please let us know if you need any further help :) we can even set up a short call and discuss. Happy weekend o/

**Comment by sparticvs** [comment]
Closing this as irrelevant now that it seems to trigger correctly.
